//  QUESTION 1-A CASHIER WANTS NEEDS TO ADD TWO AMOUNTS ENTERED BY A CUSTOMER QUICKLY . IMPLEMENT A SOLUTION TO ACCEPT TWO NUMBER AND COMPUTE THEIR SUM
// #include <iostream>
// using namespace std;

// int main() {
//     int A1,A2, sum;
//     cout<<" enter amount 1"<<endl<<"enter amount 2"<<endl;
//     cin>>A1>>A2;
//     sum=A1+A2;
//     cout<< "The sum of the amount is:"<<sum<<endl;
//     return 0;
// }

// Q2- A TEACHER WANTS T0 FIND THE AVERAGE MARKS OF THREE STUDENTS TO DECIDE CLASS PERFORMANCE.IMPLEMENT A SOLN TO ACCEPT THREE NUMBERS AND COMPUTE THEIR AVERAGE.
// #include <iostream>
// using namespace std;

// int main() {
//     int S1,S2,S3,AVERAGE;
//     cout<<"enter student 1 marks"<<endl<<"enter student 2 marks"<<endl<<"enter student 3 marks"<<endl;
//     cin>>S1>>S2>>S3;
//     AVERAGE=S1+S2+S3/3;
//     cout<<"the average of the class is :"<<AVERAGE<<endl;
//     return 0;
// }


// Q3-AN ARCHITECT WANTS TO CALCULATE THE SPACE COVERED BY A CIRCULAR FOUNTAIN. IMPLEMENT A SOLN. TO COMPUTE THE AREA OF CIRCLE
// #include <iostream>
// using namespace std;

// int main() {
//     float A,r,pi;
//     cout<<"enter radius of circle"<<endl;
//     cin>>r;
//     pi=3.14;
//     A=pi*r*r;
//     cout<<"the area of circle is :"<<A<<endl;
    
    
//     return 0;
// }


// Q4-A weather app developer needs to provide both Celsius and Fahrenheit readings. Implement a solution to 
// convert Fahrenheit temperature into Centigrade or vice versa. 

// #include <iostream>
// using namespace std;

// int main() {
//     int f ,c;
//     cout<<"enter temperature in fahrenheit:";
//     cin>>f;
//     c=(f-32)*5/9;
//     cout<<"temperature in centigrate is:"<<c<<endl;
    
//     return 0;
// }

//  Q5-A shopkeeper wants to calculate the total bill amount after applying a 20% discount on the purchase. 
// Implement a solution to accept item no., quantity, and unit price. Compute the amount and apply 20% discount. 

// #include <iostream>
// using namespace std;

// int main() {
//     int a,b,c,total,discount;
//     cout<<"enter total item no.: \n enter quantity\n enter unit price";
//     cin>>a>>b>>c;
//     total=b*c;
//     cout<<"total amount before the discount is :"<<total<<endl;
//     discount=total-(total*0.2);
//     cout<<"total amount after the discount is:"<<discount<<endl;

//     return 0;
// }


// Q6-A student wants to swap the values of two variables for practising coding basics. 
// Implement a solution to swap two numbers using different techniques.

// METHOD 1-

// #include <iostream>
// using namespace std;

// int main() {
//     float x,y;
//     cout<<"ENTER THE VALUE OF X AND Y";
//     cin>>x>>y;
//     cout<<"the value of x and y after swapping is :"<<y<<endl<<x<<endl;
//     return 0;
// }

// METHOD-2

// #include <iostream>
// using namespace std;

// int main() {
//     float x=12,y=11;
//     cout<<"the value of x and y is :"<<x<<" "<<y<<endl;
//     cout<<"the value of x and y after swapping is:"<<y<<" "<<x<<endl;
//     return 0;
// }

