//  QUESTION 1-A CASHIER WANTS NEEDS TO ADD TWO AMOUNTS ENTERED BY A CUSTOMER QUICKLY . IMPLEMENT A SOLUTION TO ACCEPT TWO NUMBER AND COMPUTE THEIR SUM
// #include <iostream>
// using namespace std;

// int main() {
//     int A1,A2, sum;
//     cout<<" enter amount 1"<<endl<<"enter amount 2"<<endl;
//     cin>>A1>>A2;
//     sum=A1+A2;
//     cout<< "The sum of the amount is:"<<sum<<endl;
//     return 0;
// }

// Q2- A TEACHER WANTS T0 FIND THE AVERAGE MARKS OF THREE STUDENTS TO DECIDE CLASS PERFORMANCE.IMPLEMENT A SOLN TO ACCEPT THREE NUMBERS AND COMPUTE THEIR AVERAGE.
// #include <iostream>
// using namespace std;

// int main() {
//     int S1,S2,S3,AVERAGE;
//     cout<<"enter student 1 marks"<<endl<<"enter student 2 marks"<<endl<<"enter student 3 marks"<<endl;
//     cin>>S1>>S2>>S3;
//     AVERAGE=S1+S2+S3/3;
//     cout<<"the average of the class is :"<<AVERAGE<<endl;
//     return 0;
// }